# PostgreSQL Client Authentication Configuration File
# 主库认证配置

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
host    all             all             10.0.0.0/8              trust
host    all             all             172.16.0.0/12           trust
host    all             all             192.168.0.0/16          trust

# 允许复制连接
local   replication     repl_user                               trust
host    replication     repl_user       127.0.0.1/32            trust
host    replication     repl_user       10.0.0.0/8              trust
host    replication     repl_user       172.16.0.0/12           trust
host    replication     repl_user       192.168.0.0/16          trust
# 允许本机从库连接主库
host    replication     repl_user       host.docker.internal/32 trust