# Configuration file for Go backend
# This file contains default settings that can be overridden by environment variables

server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  name: "main_db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

auth:
  jwt_secret: "dev-secret-key"
  jwt_expiration: 24h
  password_cost: 10

logging:
  level: "debug"
  format: "json"
  output: "stdout"

cors:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  allow_credentials: true

app:
  name: "AI Project Management Backend"
  version: "1.0.0"
  environment: "development"