#!/bin/bash
#
# Xcode项目创建指导脚本
# 由于无法通过命令行直接创建完整的Xcode项目，此脚本提供详细的步骤指导
#

set -e

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                   iOS应用 - Xcode项目创建指南                     ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

# 项目信息
PROJECT_NAME="AI-Proj-iOS"
BUNDLE_ID="com.aiproj.mobile"
TEAM_ID="个人团队"  # 需要在Xcode中配置

echo "📋 项目信息:"
echo "   • 项目名称: $PROJECT_NAME"
echo "   • Bundle ID: $BUNDLE_ID"
echo "   • 最低版本: iOS 15.0"
echo "   • 界面框架: SwiftUI"
echo "   • 架构模式: MVVM + Clean Architecture"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 步骤 1: 打开Xcode并创建新项目"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  打开Xcode"
echo "    命令: open -a Xcode"
echo ""
read -p "    按回车继续 (将自动打开Xcode)... "
open -a Xcode
sleep 2
echo ""

echo "2️⃣  在Xcode中:"
echo "    a) 点击 \"Create a new Xcode project\""
echo "    b) 选择 \"iOS\" → \"App\""
echo "    c) 点击 \"Next\""
echo ""
read -p "    完成后按回车继续..."
echo ""

echo "3️⃣  配置项目信息:"
echo "    • Product Name: $PROJECT_NAME"
echo "    • Team: (选择你的Apple ID，或稍后配置)"
echo "    • Organization Identifier: com.aiproj"
echo "    • Bundle Identifier: $BUNDLE_ID"
echo "    • Interface: SwiftUI"
echo "    • Language: Swift"
echo "    • 取消勾选: Include Tests (我们已有测试文件)"
echo ""
read -p "    配置完成后按回车继续..."
echo ""

echo "4️⃣  选择保存位置:"
echo "    建议选择: $(dirname "$(pwd)")"
echo "    项目文件夹名: $PROJECT_NAME"
echo ""
read -p "    保存完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 步骤 2: 删除默认文件并准备导入"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "在Xcode中删除以下自动生成的文件 (右键 → Delete → Move to Trash):"
echo ""
echo "   • ContentView.swift"
echo "   • ${PROJECT_NAME}App.swift (如果存在)"
echo ""
echo "保留以下文件:"
echo "   • Assets.xcassets"
echo "   • Preview Content"
echo ""
read -p "删除完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📂 步骤 3: 导入源代码文件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 统计文件数量
SWIFT_FILE_COUNT=$(find . -name "*.swift" | wc -l | tr -d ' ')
DIR_COUNT=$(find . -maxdepth 1 -type d ! -name ".*" ! -name "Preview Content" | wc -l | tr -d ' ')
DIR_COUNT=$((DIR_COUNT - 1))  # 减去当前目录

echo "准备导入 $SWIFT_FILE_COUNT 个Swift文件，组织在 $DIR_COUNT 个目录中"
echo ""
echo "📁 目录结构:"
echo ""
find . -maxdepth 1 -type d ! -name ".*" ! -name "Preview Content" ! -name "." | sort | while read dir; do
    if [ "$dir" != "." ]; then
        dirname=$(basename "$dir")
        file_count=$(find "$dir" -name "*.swift" | wc -l | tr -d ' ')
        echo "   📂 $dirname/ ($file_count 个文件)"
    fi
done
echo ""

echo "导入步骤:"
echo ""
echo "1️⃣  在Finder中打开当前目录:"
echo "    命令: open ."
echo ""
read -p "    按回车打开Finder... "
open .
sleep 1
echo ""

echo "2️⃣  将以下文件夹拖入Xcode项目导航器 (左侧面板):"
echo ""
echo "    ✅ AI_Proj_iOS_App.swift (应用入口)"
echo "    ✅ Config.swift (配置文件)"
echo "    ✅ Info.plist (项目配置)"
echo "    ✅ Models/ (所有数据模型)"
echo "    ✅ Core/ (核心功能)"
echo "    ✅ Data/ (数据层)"
echo "    ✅ Features/ (功能模块)"
echo "    ✅ UI/ (UI组件)"
echo "    ✅ Tests/ (测试文件)"
echo ""
echo "⚠️  重要: 拖入时请确保勾选:"
echo "    • ✅ Copy items if needed"
echo "    • ✅ Create groups"
echo "    • ✅ Add to targets: $PROJECT_NAME"
echo ""
read -p "    导入完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚙️  步骤 4: 配置项目设置"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  在Xcode中选择项目文件 (左侧最顶部的蓝色图标)"
echo ""
echo "2️⃣  在 \"General\" 标签页中:"
echo "    • Display Name: AI项目管理"
echo "    • Deployment Target: iOS 15.0"
echo "    • iPhone Orientation: ✅ Portrait, ✅ Landscape Left, ✅ Landscape Right"
echo ""
read -p "    配置完成后按回车继续..."
echo ""

echo "3️⃣  在 \"Info\" 标签页中:"
echo "    • 右键点击 Custom iOS Target Properties"
echo "    • 选择 Add Row"
echo "    • 添加以下键值对:"
echo "      - NSAppTransportSecurity → NSAllowsArbitraryLoads: YES"
echo "        (允许HTTP请求，仅开发环境)"
echo ""
read -p "    配置完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 步骤 5: 配置Apple ID和代码签名"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  添加Apple ID (如果还没有添加):"
echo "    • Xcode → Settings (⌘,)"
echo "    • 选择 \"Accounts\" 标签"
echo "    • 点击左下角的 \"+\" 按钮"
echo "    • 选择 \"Apple ID\""
echo "    • 输入你的Apple ID和密码"
echo ""
read -p "    添加完成后按回车继续..."
echo ""

echo "2️⃣  配置代码签名:"
echo "    • 在项目设置中选择 \"Signing & Capabilities\" 标签"
echo "    • ✅ 勾选 \"Automatically manage signing\""
echo "    • Team: 选择你的Apple ID (Personal Team)"
echo "    • Bundle Identifier: $BUNDLE_ID"
echo ""
read -p "    配置完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 步骤 6: 连接iPhone并信任开发者"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  连接iPhone到Mac (使用USB线)"
echo ""
echo "2️⃣  在iPhone上点击 \"信任此电脑\""
echo ""
echo "3️⃣  检查连接状态:"
read -p "    按回车检查iPhone连接..."
echo ""
bash check_device.sh
echo ""

echo "4️⃣  在Xcode中:"
echo "    • 顶部工具栏选择你的iPhone设备 (而不是模拟器)"
echo "    • 如果看不到设备，请:"
echo "      - Window → Devices and Simulators (⇧⌘2)"
echo "      - 确认你的iPhone出现在列表中"
echo ""
read -p "    设备选择完成后按回车继续..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 步骤 7: 构建并运行"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  点击 Xcode 左上角的 \"Play\" 按钮 (或按 ⌘R)"
echo ""
echo "2️⃣  首次运行可能会:"
echo "    • 需要输入Mac密码 (用于代码签名)"
echo "    • 下载调试符号 (如果设备是新连接的)"
echo "    • 编译时间较长 (首次构建)"
echo ""
echo "3️⃣  如果遇到 \"Untrusted Developer\" 错误:"
echo "    • 在iPhone上: 设置 → 通用 → VPN与设备管理"
echo "    • 找到你的Apple ID"
echo "    • 点击 \"信任\""
echo ""
read -p "    按回车开始构建..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 项目统计"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   📄 Swift文件总数: $SWIFT_FILE_COUNT"
echo "   📂 目录总数: $DIR_COUNT"
echo "   🏗️  架构模式: MVVM + Clean Architecture"
echo "   🎨 UI框架: SwiftUI"
echo "   🔄 状态管理: Combine + @Published"
echo "   🌐 网络层: URLSession + Combine"
echo "   💾 数据持久化: UserDefaults + Cache"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 完成检查清单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   ☐ Xcode项目已创建"
echo "   ☐ 所有源代码文件已导入"
echo "   ☐ Info.plist配置正确"
echo "   ☐ Apple ID已添加"
echo "   ☐ 代码签名配置完成"
echo "   ☐ iPhone已连接并信任"
echo "   ☐ 应用成功运行在iPhone上"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 常见问题解决"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ 问题1: 无法找到iPhone设备"
echo "   ✅ 解决: 检查USB线连接，在iPhone上点击\"信任\""
echo ""
echo "❌ 问题2: 代码签名失败"
echo "   ✅ 解决: 确认Apple ID已添加，Team选择正确"
echo ""
echo "❌ 问题3: Bundle ID冲突"
echo "   ✅ 解决: 更改Bundle ID为唯一值 (如: com.yourname.aiproj)"
echo ""
echo "❌ 问题4: 编译错误"
echo "   ✅ 解决: Product → Clean Build Folder (⇧⌘K)，然后重新构建"
echo ""
echo "❌ 问题5: \"Untrusted Developer\""
echo "   ✅ 解决: iPhone设置 → 通用 → VPN与设备管理 → 信任开发者"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 完成后，你的AI项目管理应用将在iPhone上运行！"
echo ""
echo "📖 更多帮助: "
echo "   • Xcode文档: https://developer.apple.com/documentation/"
echo "   • Swift文档: https://docs.swift.org/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
