#!/bin/bash

##############################################################################
# TaskDetail 全量发布执行脚本
#
# 用途: 执行TaskDetail组件的100%全量发布
# 阶段: Phase 4 - Day 3
# 执行时间: Phase 3验证成功后
##############################################################################

set -e  # 遇到错误立即退出

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查依赖
check_dependencies() {
    log_info "检查依赖..."

    if ! command -v node &> /dev/null; then
        log_error "Node.js 未安装"
        exit 1
    fi

    if ! command -v npm &> /dev/null; then
        log_error "npm 未安装"
        exit 1
    fi

    if ! command -v git &> /dev/null; then
        log_error "git 未安装"
        exit 1
    fi

    log_success "依赖检查完成"
}

# 备份当前配置
backup_current_config() {
    log_info "备份当前配置..."

    BACKUP_DIR="./backups/$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$BACKUP_DIR"

    # 备份关键文件
    cp frontend/src/App.tsx "$BACKUP_DIR/" 2>/dev/null || true
    cp frontend/src/index.tsx "$BACKUP_DIR/" 2>/dev/null || true
    cp frontend/src/config/featureFlagConfig.ts "$BACKUP_DIR/" 2>/dev/null || true

    log_success "配置已备份到: $BACKUP_DIR"
    echo "$BACKUP_DIR" > .last_backup_path
}

# 验证构建
verify_build() {
    log_info "验证构建..."

    cd frontend
    npm run build

    if [ $? -ne 0 ]; then
        log_error "构建失败"
        exit 1
    fi

    log_success "构建验证成功"
    cd ..
}

# 执行全量发布
execute_full_release() {
    log_info "执行100%全量发布..."

    # 检查当前灰度比例
    log_info "当前灰度配置:"
    cat frontend/src/config/featureFlagConfig.ts | grep -A 5 "productionFeatureFlags"

    # 确认执行
    echo ""
    log_warning "即将执行100%全量发布,所有用户将使用新版TaskDetail"
    read -p "是否继续? (yes/no): " confirm

    if [ "$confirm" != "yes" ]; then
        log_info "发布已取消"
        exit 0
    fi

    # 更新配置为100%
    log_info "更新特性开关配置为100%..."

    # 配置已经在代码中设置为100%,这里只是确认
    log_success "特性开关已配置为100%"

    # 构建生产版本
    log_info "构建生产版本..."
    cd frontend
    NODE_ENV=production npm run build
    cd ..

    log_success "全量发布执行完成"
}

# 部署到生产环境
deploy_to_production() {
    log_info "准备部署到生产环境..."

    # 这里根据实际部署方式调整
    # 示例:
    # - rsync到服务器
    # - docker build & push
    # - kubernetes apply
    # - 等等

    log_warning "请根据实际部署流程执行部署操作"
    log_info "构建产物位于: frontend/build/"

    # 示例部署命令 (需要根据实际情况调整)
    # rsync -avz frontend/build/ user@server:/var/www/html/
    # docker build -t myapp:latest frontend/
    # docker push myapp:latest

    log_success "部署准备完成"
}

# 验证发布
verify_deployment() {
    log_info "验证发布..."

    # 这里可以添加健康检查
    # curl http://your-app.com/health
    # 等等

    log_info "请手动验证以下内容:"
    echo "  1. 访问应用: http://your-app.com"
    echo "  2. 检查TaskDetail页面是否正常"
    echo "  3. 检查错误监控Dashboard"
    echo "  4. 检查性能监控Dashboard"
    echo "  5. 查看用户反馈"

    log_success "发布验证指南已显示"
}

# 创建发布记录
create_release_record() {
    log_info "创建发布记录..."

    RELEASE_LOG="./docs/releases/$(date +%Y%m%d_%H%M%S)_full_release.md"
    mkdir -p "./docs/releases"

    cat > "$RELEASE_LOG" << EOF
# TaskDetail全量发布记录

## 发布信息
- **发布时间**: $(date '+%Y-%m-%d %H:%M:%S')
- **发布版本**: Phase 4 - 100% Full Release
- **执行人**: $(git config user.name)
- **Git Commit**: $(git rev-parse HEAD)

## 发布配置
- **灰度比例**: 100%
- **特性开关**: NEW_TASK_DETAIL = enabled
- **目标用户**: 全部用户

## 构建信息
- **Node版本**: $(node --version)
- **npm版本**: $(npm --version)
- **构建时间**: $(date '+%Y-%m-%d %H:%M:%S')

## 备份信息
- **备份路径**: $(cat .last_backup_path 2>/dev/null || echo "无")

## 验证清单
- [ ] 应用可访问
- [ ] TaskDetail页面正常
- [ ] 错误率正常
- [ ] 性能指标正常
- [ ] 用户反馈正常

## 后续监控
- 持续监控24小时
- 收集用户反馈
- 分析性能数据
- 准备问题修复

---
🤖 Generated by deploy-full-release.sh
EOF

    log_success "发布记录已创建: $RELEASE_LOG"
}

# 主函数
main() {
    echo ""
    echo "=========================================="
    echo "  TaskDetail 全量发布执行脚本"
    echo "  Phase 4 - Day 3: 100% Full Release"
    echo "=========================================="
    echo ""

    # 执行步骤
    check_dependencies
    backup_current_config
    verify_build
    execute_full_release
    deploy_to_production
    verify_deployment
    create_release_record

    echo ""
    log_success "=========================================="
    log_success "  全量发布执行完成!"
    log_success "=========================================="
    echo ""

    log_info "下一步操作:"
    echo "  1. 访问灰度管理面板: http://localhost:3000/admin/gray-release"
    echo "  2. 确认灰度比例为100%"
    echo "  3. 监控系统指标"
    echo "  4. 收集用户反馈"
    echo "  5. 如有问题执行回滚: ./scripts/rollback.sh"
    echo ""
}

# 执行主函数
main "$@"
