#!/bin/bash

##############################################################################
# TaskDetail 快速回滚脚本
#
# 用途: 在发现问题时快速回滚到稳定版本
# 支持多种回滚级别
##############################################################################

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Level 1: 灰度回滚 (最快 - 1分钟)
rollback_level1() {
    log_warning "执行 Level 1 灰度回滚..."

    echo "请访问灰度管理面板执行以下操作:"
    echo "  1. 打开: http://localhost:3000/admin/gray-release"
    echo "  2. 将灰度比例降低: 100% → 50% → 20% → 5% → 0%"
    echo "  3. 或点击'关闭灰度 (0%)'按钮"
    echo ""
    echo "也可以在浏览器Console执行:"
    echo "  FeatureFlagService.setRolloutPercentage(FeatureFlag.NEW_TASK_DETAIL, 0);"
    echo "  FeatureFlagService.setEnabled(FeatureFlag.NEW_TASK_DETAIL, false);"

    log_success "灰度回滚指南已显示"
}

# Level 2: 路由回滚 (快速 - 5-10分钟)
rollback_level2() {
    log_warning "执行 Level 2 路由回滚..."

    # 检查备份
    if [ -f .last_backup_path ]; then
        BACKUP_DIR=$(cat .last_backup_path)
        log_info "找到备份: $BACKUP_DIR"

        # 恢复配置文件
        if [ -f "$BACKUP_DIR/App.tsx" ]; then
            cp "$BACKUP_DIR/App.tsx" frontend/src/App.tsx
            log_success "已恢复 App.tsx"
        fi

        if [ -f "$BACKUP_DIR/featureFlagConfig.ts" ]; then
            cp "$BACKUP_DIR/featureFlagConfig.ts" frontend/src/config/featureFlagConfig.ts
            log_success "已恢复 featureFlagConfig.ts"
        fi
    else
        log_warning "未找到备份,需要手动修改代码"
        echo ""
        echo "请手动修改 frontend/src/App.tsx:"
        echo "  将 TaskDetailRouter 改为 TaskDetailPageNew"
    fi

    # 重新构建
    log_info "重新构建应用..."
    cd frontend
    npm run build
    cd ..

    log_success "路由回滚完成,请重新部署"
}

# Level 3: Git回滚 (完整 - 15-30分钟)
rollback_level3() {
    log_warning "执行 Level 3 Git回滚..."

    # 显示最近的提交
    log_info "最近的提交历史:"
    git log --oneline -10

    echo ""
    read -p "请输入要回滚到的commit hash: " commit_hash

    if [ -z "$commit_hash" ]; then
        log_error "未输入commit hash"
        exit 1
    fi

    # 确认回滚
    log_warning "即将回滚到: $commit_hash"
    git log -1 "$commit_hash"
    echo ""
    read -p "确认回滚? (yes/no): " confirm

    if [ "$confirm" != "yes" ]; then
        log_info "回滚已取消"
        exit 0
    fi

    # 执行回滚
    log_info "执行git回滚..."
    git reset --hard "$commit_hash"

    # 重新安装依赖并构建
    log_info "重新安装依赖..."
    cd frontend
    npm install
    npm run build
    cd ..

    log_success "Git回滚完成,请重新部署"
}

# 创建回滚记录
create_rollback_record() {
    local level=$1
    local reason=$2

    ROLLBACK_LOG="./docs/rollbacks/$(date +%Y%m%d_%H%M%S)_rollback_level${level}.md"
    mkdir -p "./docs/rollbacks"

    cat > "$ROLLBACK_LOG" << EOF
# TaskDetail回滚记录

## 回滚信息
- **回滚时间**: $(date '+%Y-%m-%d %H:%M:%S')
- **回滚级别**: Level $level
- **执行人**: $(git config user.name)
- **触发原因**: ${reason:-未指定}

## 回滚前状态
- **Git Commit**: $(git rev-parse HEAD)
- **灰度比例**: 100%

## 回滚操作
$(if [ "$level" == "1" ]; then
    echo "- 通过灰度管理面板降低灰度比例"
elif [ "$level" == "2" ]; then
    echo "- 恢复路由配置"
    echo "- 重新构建应用"
elif [ "$level" == "3" ]; then
    echo "- Git回滚到稳定版本"
    echo "- 重新安装依赖"
    echo "- 重新构建应用"
fi)

## 验证清单
- [ ] 应用可访问
- [ ] 功能正常
- [ ] 错误率恢复
- [ ] 用户可使用

## 后续行动
- [ ] 问题根因分析
- [ ] 修复方案制定
- [ ] 回归测试
- [ ] 准备重新发布

---
🤖 Generated by rollback.sh
EOF

    log_success "回滚记录已创建: $ROLLBACK_LOG"
}

# 主函数
main() {
    echo ""
    echo "=========================================="
    echo "  TaskDetail 快速回滚脚本"
    echo "=========================================="
    echo ""

    echo "请选择回滚级别:"
    echo "  1) Level 1 - 灰度回滚 (最快, 1分钟)"
    echo "  2) Level 2 - 路由回滚 (快速, 5-10分钟)"
    echo "  3) Level 3 - Git回滚 (完整, 15-30分钟)"
    echo ""
    read -p "请输入选择 (1/2/3): " level

    case $level in
        1)
            rollback_level1
            ;;
        2)
            rollback_level2
            ;;
        3)
            rollback_level3
            ;;
        *)
            log_error "无效的选择"
            exit 1
            ;;
    esac

    echo ""
    read -p "请输入回滚原因 (可选): " reason
    create_rollback_record "$level" "$reason"

    echo ""
    log_success "=========================================="
    log_success "  回滚操作完成!"
    log_success "=========================================="
    echo ""

    log_info "后续操作:"
    echo "  1. 验证系统功能"
    echo "  2. 检查错误率"
    echo "  3. 分析问题原因"
    echo "  4. 制定修复方案"
    echo ""
}

main "$@"
